### ISSUE TITLE
似乎是找不到二维码图片?

### ISSUE THREAD

**Issue by mixosense-zhihaozhou** [panxingfeng/agent_chat_wechat#2]
[2024-10-31 21:19:44][ERROR]: 启动时发生错误: [WinError 2] 系统找不到指定的文件。
[2024-10-31 21:19:44][ERROR]: 错误详情：
Traceback (most recent call last):
  File "D:\CODE\WECHAT2\agent_chat_wechat\main.py", line 162, in main_task
    await core.auto_login(hot_reload=False)
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\site-packages\vchat\core\register.py", line 51, in auto_login
    await self._login(
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\site-packages\vchat\core\login.py", line 43, in _login
    resp_text = await self._get_uuid_and_wait_for_scan(
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\site-packages\vchat\core\login.py", line 107, in _get_uuid_and_wait_for_scan
    await self.get_qr(self.uuid, enable_cmd_qr, pic_path, qr_callback)
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\site-packages\vchat\core\login.py", line 81, in get_qr
    utils.print_qr(pic_path)
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\site-packages\vchat\utils.py", line 85, in print_qr
    subprocess.call(["start", file_path])
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ProgramData\anaconda3\envs\WeCHART\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
[2024-10-31 21:19:44][INFO]: 程序退出。

**Comment by panxingfeng** [comment]
我的猜测是系统环境的问题，这个是VChat框架的问题，我在部署到我朋友的电脑发现了这个问题，在我自己笔记本，主机目前是没有这个问题

**Comment by panxingfeng** [comment]
我的猜测是电脑系统环境的问题，我在部署到我朋友的电脑也发现了这个问题，在我自己笔记本/主机和其他朋友的电脑，目前是没有出现这个问题，我后面有时间整一下这个问题

**Comment by panxingfeng** [comment]
我后续有时间，解决一下这个问题，在我其中的一个朋友电脑上有出现这个问题，其他朋友的电脑是都没问题的

**Comment by panxingfeng** [comment]
解决问题的办法就是：
根据你的路径设置，打开D:\ProgramData\anaconda3\envs\WeCHART\lib\site-packages\vchat\utils.py这个文件，
找到：print_qr函数

替换下列代码：
def print_qr(file_path):
    if config.OS == "linux":
        subprocess.call(["xdg-open", file_path])
    elif config.OS == "win32":
        subprocess.call(["explorer", file_path])
    elif config.OS == "darwin":
        subprocess.call(["open", file_path])
    else:
        raise NotImplementedError

**Comment by panxingfeng** [comment]
如果二维码没有打开，在项目文件夹下会有一个svg的文件，打开以后扫码即可，登录的微信号一定要实名认证过的账号
